---
title: "Oxford Data"
output: html_notebook
---

```{r setup, echo=FALSE}
library(RCurl)
library(tidyverse)
library(janitor)
library(countrycode)
```

```{r}
mena.countries <- read_csv('./mena.csv') %>% clean_names()
```

# COVID Cases Statistics

```{r}
owid.covid.url <- getURL("https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv")
owid.covid.mena <- read.csv(text = owid.covid.url) %>%
  clean_names() %>%
  filter(iso_code %in% mena.countries$iso3) %>%
  # Jessie Request: remove empty columns to avoid non-updated data rows
  filter(!is.na(total_cases)) %>%
  # Keep the clean data
  select(iso_code, date, total_cases, new_cases, new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed)

owid.covid.mena %>%
  write.csv("../Demographics/MENAR-CountriesCOVID.csv")
```

# COVID Vaccination Statistics

## Step 1: Read Data from OWID

```{r}
owid.vaccine.url <- "https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/country_data/"

owid.mena.list <- list("United%20Arab%20Emirates", 
                    "Bahrain", 
                    "Algeria", 
                    "Egypt", 
                    "Iraq", 
                    "Israel",
                    "Jordan", 
                    "Kuwait", 
                    "Lebanon", 
                    "Morocco", 
                    "Mauritania", 
                    "Oman", 
                    "Palestine", 
                    "Qatar", 
                    "Saudi%20Arabia",
                    "Sudan",
                    "Syria", 
                    "Tunisia")

map_to_vaccine <- function(x) {
 
  country_path <- paste0(owid.vaccine.url, x, ".csv")
  country.vaccine.url <- getURL(country_path)
  
  owid.vaccine.country <- read.csv(text = country.vaccine.url) %>%
    clean_names() %>%
    select(location, Date = date, Total_Vaccinations = total_vaccinations, Source_url = source_url)
  return(owid.vaccine.country)
}

owid.mena.vaccine <- owid.mena.list %>%
  map_dfr(map_to_vaccine)

owid.mena.vaccine$Country <- countrycode( owid.mena.vaccine$location,origin = 'country.name', destination = 'iso3c') 


owid.mena.vaccine <- owid.mena.vaccine %>%
  select(-location) %>%
  select(Country, everything())

owid.mena.vaccine %>%  write.csv("../Distribution/OWID-Vaccine-Progress.csv") 

```

## Step 2: Merge Data from DSI Dataset

```{r}
# Add another file to read that Jessie and team will build manually
# TODO: Review the QA process on how to clean the data in case of duplicates.
covid.dsi.manual.url <- getURL("https://raw.githubusercontent.com/inception-labs/covid-vaccine-mena/main/Distribution/Manual-Vaccine-Progress.csv")

dsi.vaccine.data <- read.csv(text = covid.dsi.manual.url) %>%
  clean_names() %>%
  mutate(total_vaccinations = total_vaccinated + one_dose) %>%
  select(country, date, total_vaccinations) %>%
  filter(!is.na(total_vaccinations)) %>%
  mutate(source="manual")
  

owid.mena.vaccine.simplified <- owid.mena.vaccine %>% clean_names() %>%
  select(country, date, total_vaccinations) %>%
  filter(!is.na(total_vaccinations)) %>%
  mutate(source="owid")

combined.mena.vaccine <-  rbind(dsi.vaccine.data, owid.mena.vaccine.simplified) %>%
  arrange(country, date) 

combined.mena.vaccine %>%  write.csv("../Distribution/Total-Vaccine-Progress.csv") 
```

