name: .github/workflows
on:
  push:
    branches:
      - main
  schedule:
    - cron: '38 22 * * 0-6'
jobs:
  build:
    runs-on: macOS-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}    
      - name: Install papermill
        run: |
         pip install papermill
         pip install plotly
         pip install pandas
         pip install numpy
         pip install pandas-bokeh
         pip install matplotlib
         pip install seaborn
         python -m pip install ipykernel
         pip install ipywidgets
      - name: Running
        run: |
         papermill Scripts/Menar_Covid_Country_Investigation_Tunisia.ipynb  Scripts/Menar_Covid_Country_Investigation_Tunisia.ipynb
         